sudo: required
services:
    - docker
language: node_js
node_js: node
before_script:
    - docker-compose up -d
    - while [[ "$(curl -w '%{http_code}' --silent --output /dev/null http://localhost:8080/wp-json/wp/v2)" != '200' ]]; do sleep 1; done
script: npm run travis
branches:
    only:
        - master
        - /^greenkeeper-.*$/
cache: yarn
