import axios from 'axios';
import { GraphQLFieldConfigMap, GraphQLObjectType, GraphQLSchema } from 'graphql';
import GraphqlJSTransport from 'lokka-transport-graphql-js';
import bootstrapPostResolvers, { CustomPostTypeParams } from './lib/core/bootstrapPostResolvers';
import parseMeta from './lib/core/metaParser';
import queryString from './lib/core/queryString';
import defaultMutations from './models/mutations';
import defaultQueries from './models/queries';
import defaultSchema from './models/schema';

export {
    defaultMutations as mutations,
    defaultQueries as queries,
    defaultSchema as schema,
};

export interface Config {
    /** Should not be used externally. */
    __INTERNAL_TESTING__?: boolean;
    /** Cookie generated by WordPress used for authentication. */
    nonce?: string;
    /** Add context to be passed to all resolvers. */
    context?: any;
    /** Custom mutations to be merged into the library upon instantiation. */
    mutations?: GraphQLFieldConfigMap<any, any>;
    /** Custom queries to be merged into the library upon instantiation. */
    queries?: GraphQLFieldConfigMap<any, any>;
    /** List of `postTypeConfig` to be merged into the library upon instantiation. */
    postTypes?: CustomPostTypeParams[];
}

export default class WPGraphQL {
    /**
     * GraphQL transport layer.
     */
    private transport;

    /**
     * @param hostUrl  The REST URL for the site up to, but not including, the namespace
     *                 and without a trailing slash.
     * @param config   An object containing configuration options for the instance.
     */
    constructor(hostUrl: string, config: Config = {}) {
        const { context, mutations: userMutations, queries: userQueries } = config;
        let mutations = { ...userMutations, ...defaultMutations };
        let queries = { ...userQueries, ...defaultQueries };

        ({ mutations, queries } = bootstrapPostResolvers({ mutations, queries }, config.postTypes));

        axios.defaults.baseURL = hostUrl;

        if (config.__INTERNAL_TESTING__) {
            axios.defaults.auth = { username: 'root', password: 'root' };
        }

        if (config.nonce) {
            axios.defaults.headers.common['X-WP-Nonce'] = config.nonce;
        }

        const schema = buildSchema({ mutations, queries });
        this.transport = new GraphqlJSTransport(schema, { rootValue: this, context });
    }
    public send(gql: string, vars?: object) {
        return this.transport.send(gql, vars).then(parseMeta);
    }
    @queryString
    protected delete(path: string, args: string): PromiseLike<any> {
        return axios.delete(`${path}${args}`).then(res => res.data);
    }
    @queryString
    protected get(path: string, args: string): PromiseLike<any> {
        return axios.get(`${path}${args}`).then(res => res.data);
    }
    protected post(path: string, args: object): PromiseLike<any> {
        return axios.post(path, parseMeta(args)).then(res => res.data);
    }
    protected upload(path: string, { file, filename, ...args }): PromiseLike<any> {
        return axios.post(path, file, {
            headers: {'Content-Disposition': `attachment;filename=${filename}`},
        }).then(res => {
            const { id } = res.data;
            return this.post(`${path}/${id}`, args);
        });
    }
}

interface BuildSchemaArgs {
    mutations: GraphQLFieldConfigMap<any, any>;
    queries: GraphQLFieldConfigMap<any, any>;
}

function buildSchema({ mutations, queries }: BuildSchemaArgs): GraphQLSchema {
    return new GraphQLSchema({
        query: new GraphQLObjectType({
            name: 'Query',
            description: 'The root query.',
            fields: () => ({ ...queries }),
        }),
        mutation: new GraphQLObjectType({
            name: 'Mutation',
            description: 'The root mutation.',
            fields: () => ({ ...mutations }),
        }),
    });
}
